# Generated by Django 4.1.5 on 2023-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заблокирован'),
        ),
    ]
