# Generated by Django 4.1.5 on 2023-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favourites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
