# Generated by Django 3.2.17 on 2023-02-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0025_item_no_pictures'),
        ('users', '0007_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_window.item', verbose_name='Объявление'),
        ),
    ]
