# Generated by Django 3.2.17 on 2023-03-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_favourites_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Название'),
        ),
    ]
