# Generated by Django 3.2.17 on 2023-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_favourites_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='name',
            field=models.CharField(blank=True, default='Охарактеризуйте тип этого объявления', max_length=80, null=True, verbose_name='Название'),
        ),
    ]
