# Generated by Django 4.1.5 on 2023-01-30 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handlers', '0002_alter_blacklist_phone_number_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Номер телефона'),
        ),
    ]
