# Generated by Django 4.1.5 on 2023-01-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0007_item_banned'),
        ('handlers', '0003_alter_blacklist_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='items',
            field=models.ManyToManyField(editable=False, to='items_window.item'),
        ),
    ]
