# Generated by Django 4.1.5 on 2023-01-30 10:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0004_blacklist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='items',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
