# Generated by Django 3.2.17 on 2023-02-20 12:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0008_auto_20230219_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'permissions': (('control_black_list', 'Контролирует черный список'),), 'verbose_name': 'Черный список', 'verbose_name_plural': 'Черный список'},
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
