# Generated by Django 3.2.17 on 2023-02-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0009_auto_20230220_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('control_reports', 'Контролирует жалобы'),), 'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
    ]
