# Generated by Django 3.2.17 on 2023-02-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0024_auto_20230221_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handlers', '0011_reportchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handlers.reportchoices', verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items_window.item', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От:'),
        ),
    ]
