# Generated by Django 3.2.17 on 2023-02-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0024_auto_20230221_1627'),
        ('handlers', '0012_auto_20230221_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items_window.item', verbose_name='Объявление'),
        ),
    ]
