# Generated by Django 4.1.5 on 2023-01-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('items_window', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geodata.region', verbose_name='Регион'),
        ),
    ]
