# Generated by Django 4.1.5 on 2023-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0002_alter_item_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
    ]
