# Generated by Django 3.2.6 on 2023-01-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0004_images_active_alter_item_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
