# Generated by Django 4.1.5 on 2023-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0005_alter_images_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликовать?'),
        ),
    ]
