# Generated by Django 4.1.5 on 2023-02-01 18:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0007_item_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='item',
            name='livin_surface',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Площадь жилая'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Этажей всего'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_surface',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Площадь общая'),
        ),
    ]
