# Generated by Django 4.1.5 on 2023-02-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0008_alter_item_floor_alter_item_livin_surface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст комментария')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='items_window.item')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
