# Generated by Django 3.2.17 on 2023-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0011_alter_item_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('rent', 'Сдам'), ('sell', 'Продам'), ('buy', 'Куплю'), ('take', 'Сниму')], max_length=15, verbose_name='Тип'),
        ),
    ]
