# Generated by Django 3.2.17 on 2023-02-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('items_window', '0013_auto_20230215_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items_window.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.region', verbose_name='Регион'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
