# Generated by Django 3.2.17 on 2023-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0014_auto_20230215_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('rent', 'Сдам'), ('sell', 'Продам'), ('buy', 'Куплю'), ('take', 'Сниму')], max_length=15, verbose_name='Тип объявления'),
        ),
    ]
