# Generated by Django 3.2.17 on 2023-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0015_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='index_store',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
