# Generated by Django 3.2.17 on 2023-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0016_images_index_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='index_store_2',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='index_store_3',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
