# Generated by Django 3.2.17 on 2023-02-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('items_window', '0017_auto_20230217_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.subregion', verbose_name='Район'),
        ),
    ]
