# Generated by Django 3.2.17 on 2023-02-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0018_item_sub_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('can_change_item', 'Может изменять объявление'), ('can_delete_item', 'Может удалить объявление')), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
