# Generated by Django 3.2.17 on 2023-02-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0019_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('can_change_item', 'Может изменять объявление'), ('can_delete_item', 'Может удалить объявление'), ('control_new_items', 'Контролирует новые объявления')), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
