# Generated by Django 3.2.17 on 2023-02-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('possible_choices', '0001_initial'),
        ('items_window', '0020_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='possible_choices.itemtypechoices', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='possible_choices.materialchoices', verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='possible_choices.typechoices', verbose_name='Тип объявления'),
        ),
    ]
