# Generated by Django 3.2.17 on 2023-02-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0024_auto_20230221_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='no_pictures',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Объявление без фотографий'),
        ),
    ]
