# Generated by Django 3.2.17 on 2023-03-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0026_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url_height',
            field=models.PositiveIntegerField(blank=True, default=1077, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='url_width',
            field=models.PositiveIntegerField(blank=True, default=1600, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='url_height', upload_to='items_img/', verbose_name='Image', width_field='url_width'),
        ),
    ]
