# Generated by Django 3.2.17 on 2023-03-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('possible_choices', '0002_auto_20230221_1628'),
        ('items_window', '0028_auto_20230302_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='possible_choices.materialchoices', verbose_name='Материал стен'),
        ),
    ]
