# Generated by Django 3.2.17 on 2023-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_window', '0029_alter_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url_height',
            field=models.PositiveIntegerField(blank=True, default=560, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='url_width',
            field=models.PositiveIntegerField(blank=True, default=400, null=True),
        ),
    ]
