# Generated by Django 3.2.17 on 2023-02-19 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Админы по регионам',
                'verbose_name_plural': 'Админы по регионам',
            },
        ),
    ]
