# Generated by Django 3.2.17 on 2023-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTypeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Возможный тип объекта',
                'verbose_name_plural': 'Возможные типы объектов',
            },
        ),
        migrations.CreateModel(
            name='MaterialChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Возможный материал',
                'verbose_name_plural': 'Возможные материалы',
            },
        ),
        migrations.CreateModel(
            name='TypeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Возможный тип объявления')),
            ],
            options={
                'verbose_name': 'Возможный тип объявления',
                'verbose_name_plural': 'Возможные типы объявлений',
            },
        ),
    ]
